//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_id { get; set; }
        public string Customer_name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
    
        public virtual City City { get; set; }
    }
}
